version: '3'
# Docker Compose 的版本

services:
  app:
    build: .
    container_name: messageboard-app-redis-ver
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - redis_rul=redis://redis:6379
      # 使用 Redis URL 替代原來的 MongoDB URL

  redis:
    image: redis:alpine
    container_name: messageboard-db-redis-ver
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  # 使用 Redis 數據卷替代 MongoDB 數據卷