version: '3'
services:
  app:
    build: .
    container_name: messageboard-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/messageBoard

  mongo:
    image: mongo:latest
    container_name: messageboard-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: